### PR TITLE
fix link to blog post

### PR DESCRIPTION
**Pull request by morenoh149**

### CODE REVIEW

**Comment by danvk** [comment]
Thanks!

**Comment by jxm262** [comment]
@danvk @morenoh149 , sorry for mentioning since it's not my project, but I think this merge broke the build :)

**Comment by jxm262** [comment]
@danvk @morenoh149  my apologies, i'll stay out of this.  looks like the build was broke before

**Comment by danvk** [comment]
I think it's just a Coveralls issue. I've pushed a [small change](https://github.com/danvk/mocha-react/commit/678efdc506dff4dbc8b4562b89349c550be86ba7) which should prevent coverage failure from breaking the build.

**Comment by danvk** [comment]
Sigh, that didn't work. I'm moving discussion over to #4.

**Pull request merged**
