### PR TITLE
Updated CheckboxWithLabel test to use mocha-jsdom.

### PR DESCRIPTION
**Pull request by benmosher**
I was unclear on what the Blanket parts are doing, so I only updated the CheckboxWithLabel test.

`npm test` yields success.

### CODE REVIEW

**Comment by danvk** [comment]
The blanket script is there for code coverage. If a module isn't included by a test, it doesn't count towards code coverage, so untested modules wouldn't count against your project. The blanket script `require`s all your source modules to count them. The thought is that some modules might not be `require`-able unless there's a `window` and `document` object, so it needs jsdom.

Your change looks great—I'll merge on green.

**Comment by danvk** [comment]
Interesting. Coveralls is [showing](https://coveralls.io/builds/2199735/source?filename=src%2FCheckboxWithLabel.js) that coverage drops in `CheckBoxWithLabel.js` as a result of this change. I can verify that that's the case locally by adding a `console.log` in `CheckBoxWithLabel.onChange`.

When I run `npm test`, I see the message. When I run

```
./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter tests/*test.js
```

I don't, whereas I did before the `mocha-jsdom` change.

**Comment by benmosher** [comment]
Looks like the `--require blanket` flag breaks the tests; it had another reference to `testdom` that I did not really understand, so I left it alone before.

Just pushed another commit that removes the reference + deletes the `testdom` module.

**Comment by danvk** [comment]
Cool, thanks for debugging!

**Pull request merged**
